#include "modbus_dev.h"

#ifndef NULL
#define NULL (0)
#endif

const ValueName ValueNamesAction[] =
{
    { 0, "Reverse", },
    { 1, "Direct", },
};

const ValueName ValueNamesDisplayUnits[] = {
    { 0, "°C", },
    { 1, "°F", },
    { 2, "K", },
    { 3, "None", },
    { 4, "%", },
};

const ValueName ValueNamesInstMode[] = {
    { 0, "Auto", },
    { 1, "Manual", },
    { 2, "Standby", },
};

const ValueName ValueNamesNULL[] = {};

const ValueName ValueNamesOffActive[] = {
    { 0, "Off", },
    { 1, "Active", },
};

const ValueName ValueNamesOnOff[] =
{
    { 0, "Off", },
    { 1, "On", },
};

const ValueName ValueNamesSensorTypes[] = {
    { 0, "J", },
    { 1, "K", },
    { 2, "L", },
    { 3, "R", },
    { 4, "B", },
    { 5, "N", },
    { 6, "T", },
    { 7, "S", },
    { 8, "RTD", },
    { 9, "milivolt", },
    { 10, "Comms Input", },
    { 11, "Custom", },
};

const ValueName ValueNamesSetpoints[] =
{
    { 0, "Setpoint 1"},
    { 1, "Setpoint 2"},
};

const ModbusReg eurotherm3216[] = {
    {
        1, "Process Value",
        true, false, true,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        2, "Target Setpoint",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        3, "Manual Output Value",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        4, "Working Output",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        5, "Working Setpoint",
        true, false, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        6, "Proportional Band",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        7, "Control Action",
        true, true, false,
        0, 1,
        NULL,
        ARRAY_SIZE(ValueNamesAction), ValueNamesAction,
    },
    {
        8, "Integral Time",
        true, true, false,
        0, 65535,
        "Off",
        0, NULL,
    },
    {
        9, "Derivative Time",
        true, true, false,
        0, 65535,
        "Off",
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        11, "Input Range Low Limit",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12, "Input Range High Limit",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        13, "Alarm 1 Treshold",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        14, "Alarm 2 Treshold",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        15, "Active Setpoint",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesSetpoints), ValueNamesSetpoints,
    },
    {
        16, "Channel 2 Deadband",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        17, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        18, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        19, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        23, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        24, "Setpoint 1",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        25, "Setpoint 2",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        28, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        30, "Output High Limit",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        31, "Output Low Limit",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        34, "Safe Output Value",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        35, "Setpoint Rate Limit",
        true, true, false,
        0, 65535,
        "Off",
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        39, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        47, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        68, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        69, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        71, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        75, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        80, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        81, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        82, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        83, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        86, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        101, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        106, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        107, "Measured Leakage Current",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        111, "Setpoint High Limit",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        112, "Setpoint Low Limit",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        131, "Comms Address",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        141, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        146, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        199, "Instrument Mode",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesInstMode), ValueNamesInstMode,
    },
    {
        202, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        203, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        215, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        258, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        260, "New Alarm Status",
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesOffActive), ValueNamesOffActive,
    },
    {
        263, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        270, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        273, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        274, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        294, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        295, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        296, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        297, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        304, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        305, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        306, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        307, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        308, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        309, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        313, "Recipe to Recall",
        true, true, false,
        0, 5,
        "None",
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        314, "Recipe to Save",
        true, true, false,
        0, 5,
        "None",
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        320, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        321, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        322, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        323, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        324, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        325, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        326, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        327, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        328, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        512, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        513, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        514, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        515, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        516, "Display Units",
        true, true, false,
        0, 4,
        NULL,
        ARRAY_SIZE(ValueNamesDisplayUnits), ValueNamesDisplayUnits,
    },
    {
        517, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        518, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        519, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        524, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        525, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        536, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        537, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        538, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        539, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        540, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        541, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        542, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        543, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        544, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        545, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        546, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        547, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        551, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        560, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        561, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        562, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        563, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        578, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        604, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        629, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        768, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        769, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        1104, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12290, "Input Sensor Type",
        true, true, false,
        0, 11,
        NULL,
        ARRAY_SIZE(ValueNamesSensorTypes), ValueNamesSensorTypes,
    },
    {
        12291, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12306, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12307, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12352, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12353, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12361, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12544, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12548, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12549, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12550, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12608, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12609, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12610, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12672, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12673, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12675, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12678, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12679, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12680, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12681, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12682, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12706, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12736, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12739, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12742, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12743, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12744, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12745, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12746, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        12747, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        13056, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    {
        13062, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },{
        13063, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },{
        13064, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },{
        13065, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },{
        13066, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },{
        13090, NULL,
        true, true, false,
        0, 65535,
        NULL,
        ARRAY_SIZE(ValueNamesNULL), NULL,
    },
    { 0 },
};
