#include "modbus_dev.h"

#ifndef ARRAY_SIZE
#define ARRAY_SIZE(x) (sizeof(x)/sizeof(x[0]))
#endif

#ifndef NULL
#define NULL (0)
#endif

const ValueName ValueNamesAction[] =
{
    { 0, "Reverse", },
    { 1, "Direct", },
};

const ValueName ValueNamesInstMode[] = {
    { 0, "Auto", },
    { 1, "Manual", },
    { 2, "Standby", },
};

const ValueName ValueNamesNULL[] = {};

const ValueName ValueNamesOnOff[] =
{
    { 0, "Off", },
    { 1, "On", },
};

const ModbusReg eurotherm3216[] = {
    {
        1, "Process Value",
        true, false, true,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        2, "Target Setpoint",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        3, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        4, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        5, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        6, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        7, "Control Action",
        true, true, false,
        0, 1,
        -1, NULL,
        ARRAY_SIZE(ValueNamesAction), ValueNamesAction,
    },
    {
        8, "Integral Time",
        true, true, false,
        0, 65535,
        0, "Off",
        0, NULL,
    },
    {
        9, "Derivative Time",
        true, true, false,
        0, 65535,
        0, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        11, "Input Range Low Limit",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12, "Input Range High Limit",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        13, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        14, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        15, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        16, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        17, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        18, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        19, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        23, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        24, "Setpoint 1",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        25, "Setpoint 2",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        28, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        30, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        31, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        34, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        35, "Setpoint Rate Limit",
        true, true, false,
        0, 65535,
        0, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        39, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        47, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        68, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        69, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        71, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        75, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        80, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        81, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        82, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        83, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        86, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        101, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        106, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        111, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        112, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        131, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        141, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        146, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        199, "Instrument Mode",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesInstMode), ValueNamesInstMode,
    },
    {
        202, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        203, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        215, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        258, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        260, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        263, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        270, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        273, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        274, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        294, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        295, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        296, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        297, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        304, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        305, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        306, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        307, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        308, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        309, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        313, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        314, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        320, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        321, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        322, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        323, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        324, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        325, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        326, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        327, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        328, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        512, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        513, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        514, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        515, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        516, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        517, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        518, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        519, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        524, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        525, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        536, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        537, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        538, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        539, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        540, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        541, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        542, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        543, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        544, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        545, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        546, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        547, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        551, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        560, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        561, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        562, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        563, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        578, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        604, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        629, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        768, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        769, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        1104, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12290, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12291, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12306, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12307, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12352, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12353, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12361, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12544, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12548, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12549, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12550, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12608, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12609, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12610, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12672, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12673, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12675, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12678, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12679, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12680, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12681, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12682, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12706, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12736, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12739, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12742, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12743, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12744, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12745, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12746, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        12747, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        13056, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
    {
        13062, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },{
        13063, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },{
        13064, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },{
        13065, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },{
        13066, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },{
        13090, "",
        true, true, false,
        0, 65535,
        -1, "Off",
        ARRAY_SIZE(ValueNamesNULL), ValueNamesNULL,
    },
};
